Fix scenario loading to use Dungeon.load_from_generator()
The create_dungeon_from_scenario() method was incorrectly trying to create
a Dungeon with just a name, then deserialize. But Dungeon.__init__() requires
start_room_id and rooms as positional arguments.

Since we save the full generator output (dungeon_data dict), we should use
Dungeon.load_from_generator() which knows how to reconstruct the dungeon
from that format.

This fixes: TypeError: Dungeon.__init__() missing 2 required positional
arguments: 'start_room_id' and 'rooms' when loading sessions.